_novaezseoRoutes:
    resource: "@NovaeZSEOBundle/Controller/"
    type:     annotation
    prefix:   /

_novaezseo_admin_ui:
    resource: "@NovaeZSEOBundle/Controller/Admin"
    type:     annotation
